use library;

# Book
set @v1 = (select max(i.libraryCode) from Item as i) + 1;
insert into Item values (@v1,'Book','Fantasy Section','Harry Potter and the Philosopher\'s Stone','1997',0,"Fantasy", "Children");
insert into Book (libraryCode, ISBN, authors) values (@v1, 0563533390, "JK Rowling");
delete from Item_Instance where libraryCode=@v1;
insert into Item_Instance values (1, @v1, 'New');
insert into Item_Instance values (2, @v1, 'New');
insert into Item_Instance values (3, @v1, 'New');
set @v1 = @v1 + 1;
insert into Item values (@v1,'Book','Fantasy Section','Harry Potter and the Chamber of Secrets','1998',0,"Fantasy", "Children");
insert into Book (libraryCode, ISBN, authors) values (@v1, 1408810557, "JK Rowling");
delete from Item_Instance where libraryCode=@v1;
insert into Item_Instance values (1, @v1, 'New');
insert into Item_Instance values (2, @v1, 'New');
insert into Item_Instance values (3, @v1, 'New');
set @v1 = @v1 + 1;
insert into Item values (@v1,'Book','Fantasy Section','Harry Potter and the Prisoner of Azkaban','2000',0,"Fantasy", "Children");
insert into Book (libraryCode, ISBN, authors) values (@v1, 1408810565, "JK Rowling");
delete from Item_Instance where libraryCode=@v1;
insert into Item_Instance values (1, @v1, 'New');
insert into Item_Instance values (2, @v1, 'New');
insert into Item_Instance values (3, @v1, 'New');
set @v1 = @v1 + 1;
insert into Item values (@v1, "Book", "Fantasy", "Harry Potter and the Goblet of Fire", "2001", 0, "Fantasy", "Children");
insert into Item_Instance values (1, @v1, 'New');
insert into Item_Instance values (2, @v1, 'New');
insert into Item_Instance values (3, @v1, 'New');
insert into Item_Instance values (4, @v1, 'New');
insert into Item_Instance values (5, @v1, 'New');
insert into Item_Instance values (6, @v1, 'New');
insert into Item_Instance values (7, @v1, 'New');
insert into Item_Instance values (8, @v1, 'New');
insert into Item_Instance values (9, @v1, 'New');
insert into Item_Instance values (10, @v1, 'New');
insert into Item_Instance values (11, @v1, 'New');
insert into Item_Instance values (12, @v1, 'New');
insert into Item_Instance values (13, @v1, 'New');
insert into Item_Instance values (14, @v1, 'New');
